@base_url = http://localhost:3000
@access_token = <accessToken-master-key-cnm>

# Auth
# @name Login
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "admin@exemplo.com",
    "senha": "12345678"
}
###

# @name Register/CreateUser
POST  {{base_url}}/auth/register
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
    "nome": "Administrador Sistema",
    "cpf": "123.456.789-00",
    "nasc": "1990-01-01",
    "email": "admin@exemplo.com",
    "senha": "12345678",
    "senha_confirmacao": "12345678",
    "cargo": 1
}
###


# Users
# @name GetUsers
GET {{base_url}}/users
Authorization: Bearer {{access_token}}
###

# @name GetUserById
GET {{base_url}}/users/81162f25-1364-4386-8522-a19d3be8bb3b
Authorization: Bearer {{access_token}}
###

# @name PatchUser
PATCH {{base_url}}/users/81162f25-1364-4386-8522-a19d3be8bb3b
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "nome": "Administrador do Sistema",
    "ativo": true
    "senha": "12345678",
}
###

# @name DeleteUser
DELETE {{base_url}}/users/0f87ae8d-9434-445b-8f04-46a7ec65ce37
Authorization: Bearer {{access_token}}
###  

# Registers
# @name GetRegisters
GET  {{base_url}}/registers
Authorization: Bearer {{access_token}}
###

# @name GetRegisterById
GET {{base_url}}/registers/d062c3f2-381b-4dd0-8808-9814b8ce1298
Authorization: Bearer {{access_token}}
###

# @name CreateRegister
POST {{base_url}}/registers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "iduser": "0f87ae8d-9434-445b-8f04-46a7ec65ce37",
    "valor_inicial": 490.50,
    "valor_especie": 20,
    "valor_cartao": 1450,
    "valor_pix": 10,
    "valor_despesas": 75,
    "data": "2015-10-06",
    "data_final": "2015-10-08"
}
###

# @name DeleteRegister
DELETE {{base_url}}/registers/d062c3f2-381b-4dd0-8808-9814b8ce1298
Authorization: Bearer {{access_token}}
###

# Reports
# @name CreateReport
POST {{base_url}}/reports
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "iduser": "0f87ae8d-9434-445b-8f04-46a7ec65ce37",
    "data": "2015-10-02",
    "data_final": "2015-10-08"
}
###

# @name GetReports
GET {{base_url}}/reports?includeValues=true
Authorization: Bearer {{access_token}}
Content-Type: application/json
###

# @name GetReportById
GET {{base_url}}/reports/2
Authorization: Bearer {{access_token}}
Content-Type: application/json
###

# @name UpdateReport
PATCH {{base_url}}/reports/2
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "nome": "Relatório teste"
}
###

# @name DeleteReport
DELETE {{base_url}}/reports/1
Authorization: Bearer {{access_token}}
Content-Type: application/json
###

# Companies
# @name GetCompanies
GET {{base_url}}/companies
#?limit=10
#&offset=0
Authorization: Bearer {{access_token}}
###

# @name GetCompany
GET {{base_url}}/companies/1
Authorization: Bearer {{access_token}}
###

# @name CreateCompany
POST {{base_url}}/companies/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "nome": "Empresa Exemplo",
    "cnpj": "83.257.901/0001-90",
    "endereco": "Rua fulano de tal",
    "telefone": "(00) 0 0000-0000",
    "cep": "00000-000"
}
###

# @name UpdateCompany
PATCH {{base_url}}/companies/2
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "ativo": false
}
###

# @name DeleteCompany
DELETE {{base_url}}/companies/2
Authorization: Bearer {{access_token}}
###